### ISSUE TITLE
Release v1.1.2 contains files from v1.1.1

### ISSUE THREAD

**Issue by floesche** [tomickigrzegorz/zooom.js#46]
The current [release 1.1.2](https://github.com/tomickigrzegorz/zooom.js/releases/tag/v1.1.2) as well as the [CDN](https://cdn.jsdelivr.net/gh/tomickigrzegorz/zooom.js@1.1.2/dist/zooom.min.js) seem to contain v1.1.1 (at least for the `zoom.min.js` file). 

Building it locally generates the expected v1.1.2 files.

**Comment by tomickigrzegorz** [comment]
Thanks for catching this error.
